apiVersion: v1
kind: ConfigMap
data:
  nginx.conf: |
    server {
            listen 80 default_server;

            root /usr/share/nginx/html;
            index index.html;

            server_name my-website.com;

            location / {
                    try_files $uri $uri/ =404;
            }
    }
metadata:
  name: nginxconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-colin-testing
  labels:
    run: vault-agent-colin-testing
spec:
  type: NodePort
  selector:
    run: vault-agent-colin-testing
  ports:
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-colin-testing
spec:
  selector:
    matchLabels:
      run: vault-agent-colin-testing
  replicas: 2
  template:
    metadata:
      labels:
        run: vault-agent-colin-testing
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-agent-auth"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        vault.hashicorp.com/agent-set-security-context: "true"
        vault.hashicorp.com/secret-volume-path-index.html: "/usr/share/nginx/html"
        # Transit Secrets Engine Value
        vault.hashicorp.com/agent-inject-secret-index.html: "transit/encrypt/orders"
        vault.hashicorp.com/agent-inject-template-index.html: |
          <html>
          <head>
          <title>Vault Transit Secrets Engine Demo</title>
          </head>
          <body>
          <h1>Vault Transit Secrets Engine Demo</h1>
          <p>The plaintext is 1111 2222 3333 4444</p>
          <p>The ciphertext is
          {{ $base64 := base64Encode "1111 2222 3333 4444" }}
          {{- with secret "transit/encrypt/orders" (print "plaintext=" $base64) -}}
          {{ .Data.ciphertext }}
          {{- end }}
          </p>
          </body>
          </html>
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: nginxconfigmap    
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged
        securityContext:
          runAsUser: 1000570000
          runAsGroup: 1000
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      shareProcessNamespace: true
      serviceAccountName: vault-agent-auth
---